apiVersion: v1
kind: Pod
metadata:
  name: schema-load
spec:
  containers:
    - name: schema-load
      image: pranayroot/test:5
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
      volumeMounts:
      - name: dummy
        mountPath: /dummy

  volumes:
  - name: dummy
    emptyDir:
      sizeLimit: 500Mi
