apiVersion: v1
kind: Pod
metadata:
  name: schema-load
  labels:
    component: {{ .Values.component }}
spec:
  containers:
    - name: schema-load
      image: 581798224530.dkr.ecr.us-east-1.amazonaws.com/schema-load:1.0.0
      args: [ "{{ .Values.schema.type }}", "{{ .Values.component }}" ]