apiVersion: v1
kind: Pod
metadata:
  name: schema-load
spec:
  containers:
    - name: schema-load
      image: pranayroot/test:4
      volumeMounts:
      - name: dummy
        mountPath: /dummy
      args: [ "while true; do sleep 30; done;" ]
  volumes:
  - name: dummy
    emptyDir:
      sizeLimit: 500Mi
