apiVersion: v1
kind: Pod
metadata:
  name: schema-load
  labels:
    component: shipping
spec:
  serviceAccountName: shipping
  containers:
    - name: schema-load
      image: 581798224530.dkr.ecr.us-east-1.amazonaws.com/schema-load:1.0.1
      command: ["tail", "-f", "/run.sh"]
      args: [ "mysql", "shipping" ]
      env:
      - name: env
        value: dev